name = "avisjeuxplinko-fr"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=avisjeuxplinko.fr"
HMAC_KEY = "e64663b19bdaf40511a58da76dc095db8e839880e3602be7260e4703a7713c06"
COOKIE_NAME = "z5t"
PLAY_PATH = "start"
BUTTON_ID = "p773f281f906342d03f78f87a293b58b7"
GATE_SALT = "4bb8fd97caa0aeab"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "0etn"
CTA_SELECTOR = ".play-button"
